---
- hosts: debian

  tasks:
  - name: 1. Install needed packages & Update repository
    apt: pkg={{ item }} state=installed update_cache=yes
    with_items:
          - htop
          - open-vm-tools
          - dstat
          - vim
          - git
          - wget

